
[package]
name = "todomvc"
version = "0.1.0"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
sauron = { path = "../../", default-features = false, features = ["with-dom"]}
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "0.1", optional = true }
log = "0.4"
console_log = {version ="0.2", features = ["color"]}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.web-sys]
version = "0.3"
features = ["Storage"]

[features]
with-measure = ["sauron/with-measure"]
with-storage = [] # enable disable storage
