[package]
name = "server"
version = "0.1.0"
authors = ["Greg Johnston <greg.johnston@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.2"
sauron = "0.33"
tokio = { version = "0.2", features = ["full"] }
serde_json = "1.0"

client = { path = "../client" }
