[package]
name = "csr-tailwind-trunk"
version = "0.0.0"
authors = ["Markus Kohlhase <markus.kohlhase@slowtec.de>"]
edition = "2021"
publish = false

[dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
log = "0.4"
sauron = "0.60"

[patch.crates-io]
sauron = { path = "../../" }
