[package]
name = "server"
version = "0.1.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>, Greg Johnston <greg.johnston@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3"
sauron = { path = "../../../" }
tokio = { version = "1.9", features = ["full"] }
serde_json = "1.0"
percent-encoding = "2"

client = { path = "../client" }
