[package]
name = "client"
version = "0.1.0"
authors = ["Jovansonlee Cesar<ivanceras@gmail.com>, Greg Johnston <greg.johnston@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.29"
sauron = { path = "../../../" }
console_error_panic_hook = { version = "0.1"}
log = "0.4"
console_log = {version ="0.2", features = ["color"]}
serde = { version = "1.0", features = ["serde_derive"]}
serde_json = "1.0"
